### ISSUE TITLE
Feature Request: Add index to `select entry` event

### ISSUE THREAD

**Issue by owzim** [OmarCastro/rofi-blocks#14]
The `value` aka. the label of the entry alone is not too useful most of the time. Sometimes you want to separate data from presentation.

I suggest adding an index field, which represents the index of the selected entry, starting with `0` of course.

```json
{
  "name": "select entry",
  "value": "The label of the entry",
  "index": 3
}
```

The index then can be used to map it to the item in an array which was the base to create the list and that contains additional data.

I think that should be default, but if you don't think so, than add a `property` `{{index}}` to be used in the `event format` so one can create a custom format, if needed.

**Comment by OmarCastro** [comment]
Hi @owzim, after implementing issue #20 the `data` entry is added to the entry that not only solves the problem of separating data from presentation, it is more dynamic, allowing to put any kind of information (with the correct format/encoding of course), without compromising the model of the event (this was my main concern, I prefer to not have multiple schemas for event, one for entries, and other for the other event)

Finally, I believe that this issue is solved with a different, but better solution. And for that reason, I will close this issue
