### ISSUE TITLE
Change rofi parameters

### ISSUE THREAD

**Issue by cpriest** [OmarCastro/rofi-blocks#18]
Is it possible to allow the changing of rofi parameters via the block script?

As an example, be able to change `-modi` from `combi` to `block` or change `-modi-combi` to some other new set of combinations.

I could see use in being able to change any/all command-line or config.rasi parameters via script output.  I don't know if the rofi architecture is capable of this kind of dynamic change during runtime.

### Example use case:
I like to run rofi with `-modi-combi` = `"drun,windows,block"` and if the block script recognized a specific input, such as a URL, changing `-modi` to just `block` with a single line showing to launch the given URL.

**Comment by OmarCastro** [comment]
Hello @cpriest , rofi-blocks is only supposed to change the contents of it's own modi. To allow customizability of rofi-blocks, isolation of this modi is sacrificed, which can cause issues on other modi (e.g. changing overlay label will be applied on ther modi as well).

One of the motives for this modi is exactly because the options are immuatable. Once run, it stays the same. It is a good architecture since it makes it simple, simple to maintain, simple to evolve. However, the lack of ability to change content,
anytime during runtime, limited the potential of rofi. There are some features I would like to add, but it is not feasible due to rofi architecture.

rofi-blocks has its own prefix to prevent ambiguity when configuring modi.

**Comment by cpriest** [comment]
makes sense, thanks for the reply.
